# -*- coding: utf-8 -*-
"""Fraud_Detection_transcations_part1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kuvDjdOlD3JxwbhZS4Ol-DGFHUDlTJUs
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns',100)

!unzip drive/MyDrive/kaggle/ieee-fraud-detection.zip -d /content/

!pip install --quiet autogluon

import pandas as pd
import numpy as np
from autogluon.tabular import TabularPredictor

directory = '/content/'
label = 'isFraud'
eval_metric = 'roc_auc'
save_path = directory + 'AutoGluonModels/'

train_identity = pd.read_csv(directory+'train_identity.csv')
train_transaction = pd.read_csv(directory+'train_transaction.csv')

train_data = pd.merge(train_transaction, train_identity, on='TransactionID', how='left')

train_data['isFraud'].value_counts()

from sklearn.model_selection import train_test_split
train_data, temp_data = train_test_split(train_data, test_size=0.2, random_state=42,stratify=train_data['isFraud'])
test_data, val_data = train_test_split(temp_data, test_size=0.4, random_state=42,stratify=temp_data['isFraud'])

train_data.head()

train_data.shape

train_data.info()

train_data.describe()

train_data.columns.to_list()

(train_data.isna().sum()/train_data.shape[0]).sort_values(ascending=False)

train_data['id_24'].isna().sum()

train_data = train_data[:50000]

train_data.shape

from datetime import time
predictor = TabularPredictor(label=label, eval_metric=eval_metric, path=save_path, verbosity=3).fit(
    train_data, presets='medium_quality',tuning_data=val_data, time_limit=600, num_gpus=1
)

results = predictor.fit_summary()

predictor.leaderboard()

from sklearn.metrics import roc_auc_score, roc_curve, auc
y_true = test_data[label].astype(int)
y_pred = predictor.predict(test_data.drop(columns=[label]),model='LightGBM')
AUC = roc_auc_score(y_true, y_pred)
print(AUC)

y_pred.value_counts(),y_true.value_counts()

predictor.feature_importance(test_data)

predictor.positive_class

predictor.class_labels  # classes in this list correspond to columns of predict_proba() output

y_predproba = predictor.predict_proba(test_data, as_multiclass=False)

submission = pd.read_csv(directory+'sample_submission.csv')
submission['isFraud'] = y_predproba
submission.head()
submission.to_csv(directory+'my_submission.csv', index=False)